api_options_index:
    path: /api
    defaults: { _controller: api_controller:optionsIndexAction }
    methods: [OPTIONS]

api_get_index:
    path: /api
    defaults: { _controller: api_controller:getIndexAction }
    methods: [GET]
